### ISSUE TITLE
Переезд на sqlite

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#47]
# Это meta-issue. Будет разбито на несколько конкретных мелких задач
Тут можно обсудить все неясные и просто стратегические моменты, прежде чем на отдельные задачи распиливать.
1. Почему sqlite: потому что его не надо деплоить и поддерживать. Это почему провалилась тема с postgres. На самом деле будем использовать вот [это](https://luigi.readthedocs.io/en/stable/api/luigi.contrib.sqla.html) поэтому возможно легко будет прикручивать к любой другой БД.
2. Зачем вообще БД: на файликах всё работает просто, но в реальном времени работать не сможет, да и запись файликов на диск -- это боттлнек

Что надо сделать:
- [ ] Разобраться, как работают [луиджи таски с sqlalchemy](https://luigi.readthedocs.io/en/stable/api/luigi.contrib.sqla.html) и сделать из этого гайд для следующих задач. (возможно @Avenon нам поможет)
- [ ] Сделать саму БД со схемой. Таблички, колонки и всё такое ещё предстоит обсудить. Частично зависит от предыдущего этапа. Нужно учесть, мы потом будем визуализировать не только ряды из TM.
- [ ] Написать первый luigi-task как образец. Скорее всего это я сам сделаю, но если кто-то меня опередит -- я только рад.
- [ ] Расписать ишью и требования для всех остальных тасок
- [ ] Убедиться, что всё работает ожидаемо

**Comment by Avenon** [comment]
А структура БД (схема данных), которую я делал для postgres подойдет для sqlite? Как вариант сейчас могу переписать луиджи таск с postgres на sqlite, но в той же схеме и с той же структурой - будет в качестве примера. По мере обсуждения можно будет менять структуру, так хоть какой-то первый шаг будет.

**Comment by Avenon** [comment]
И еще вопрос. Пример луиджи с sqlite выкладывать в отдельную директорию, или уже использовать существующий каталог пайплайна, потихоньку начинать его модернизировать?

**Comment by iggisv9t** [comment]
@Avenon 
Схему давай обсуждать. В файликах в принципе всё, что нужно есть, я бы не стал сильно менять. Баланс какой-то только между нормализацией и разумным числом необходимых джоинов для запросов сделать.

Луиджи-таск я имел в виду просто переделать один из уже существующих. Там же только run() у всех совсем уникальный, а всё остальное почти одинаковое.

**Comment by Avenon** [comment]
Пока только развенул sqllite и подключил sqlalchemy.

**Comment by iggisv9t** [comment]
#77
