### ISSUE TITLE
Перейти на структуру "директория под каждый источник"

### ISSUE THREAD

**Issue by iggisv9t** [newsviz/newsviz#77]
Мы решаем проблему, что если к источнику добавляются данные -- то нужно либо пересчитывать весь источник и вручную удалять этапы работы пайплайна, либо новые данные будут обрабатываться как новый источник. Сначала хотели решить это переездом на БД, но нашли более простое решение -- для каждого источника делать отдельную директорию, а каждое обновление будет отдельным файлом. Соответственно задачи по DB отменяются, изменения связанные с ней удаляем.

Нужно чтобы
- [x] Вывод имени источника происходил из названия директории в `/data/raw`
- [x] Перевести PreprocessorTask на работу с директориями под источники
- [x] Перевести ClassifierTask на работу с директориями под источники
- [x] Перевести TopicPredictorTask на работу с директориями под источники

**Comment by iggisv9t** [comment]
Ещё придумали, что надо сделать скрипт для разворачивания структуры директорий под пользовательские данные и пайплайн с автоматической генерацией конфига под них.

**Comment by iggisv9t** [comment]
#88
